### ISSUE TITLE
Problem with latest ubuntu (Disco 19.04)

### ISSUE THREAD

**Issue by sam2x** [brandleesee/ePSXe64Ubuntu#11]
Hi,

Your script were working fine under Ubuntu 18.10 (Cosmic). After my upgrade to Disco, script is failing to run. Several changes have been made to the package list.

```
NAME="Ubuntu"
VERSION="19.04 (Disco Dingo)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 19.04"
VERSION_ID="19.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=disco
UBUNTU_CODENAME=disco
```

When the script run: 

```
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
libncurses5 est déjà la version la plus récente (6.1+20181013-2ubuntu2).
unzip est déjà la version la plus récente (6.0-22ubuntu1).
libsdl-ttf2.0-0 est déjà la version la plus récente (2.0.11-6).
ecm est déjà la version la plus récente (1.03-1).
libssl1.0.0 est déjà la version la plus récente (1.0.1t-1+deb8u11).
0 mis à jour, 0 nouvellement installés, 0 à enlever et 33 non mis à jour.
--2019-06-11 16:00:51--  http://archive.ubuntu.com/ubuntu/pool/main/c/curl3/libcurl3_7.58.0-2ubuntu2_amd64.deb
Résolution de archive.ubuntu.com (archive.ubuntu.com)… 91.189.88.162, 91.189.91.23, 91.189.91.26, ...
Connexion à archive.ubuntu.com (archive.ubuntu.com)|91.189.88.162|:80… connecté.
requête HTTP transmise, en attente de la réponse… 200 OK
Taille : 214032 (209K) [application/x-debian-package]
Enregistre : «/tmp/libcurl3_7.58.0-2ubuntu2_amd64.deb»

/tmp/libcurl3_7.58.0-2ubuntu2_amd64.deb                          100%[==========================================================================================================================================================>] 209,02K  --.-KB/s    ds 0,1s    

2019-06-11 16:00:52 (2,00 MB/s) - «/tmp/libcurl3_7.58.0-2ubuntu2_amd64.deb» enregistré [214032/214032]

/home/user/ePSXe: /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0: version `OPENSSL_1.0.2' not found (required by /usr/lib/x86_64-linux-gnu/libcurl.so.3)
```
So here, version of libssl seems to mismatch : 
```
$ ls -lah /usr/lib/x86_64-linux-gnu/libssl*
-rw-r--r-- 1 root root 349K févr. 19 18:04 /usr/lib/x86_64-linux-gnu/libssl3.so
-rw-r--r-- 1 root root 978K avril  3 17:50 /usr/lib/x86_64-linux-gnu/libssl.a
lrwxrwxrwx 1 root root   13 avril  3 17:50 /usr/lib/x86_64-linux-gnu/libssl.so -> libssl.so.1.1
-rw-r--r-- 1 root root 386K mars   2 03:50 /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0
-rw-r--r-- 1 root root 572K avril  3 17:50 /usr/lib/x86_64-linux-gnu/libssl.so.1.1

$ ldd /usr/lib/x86_64-linux-gnu/libcurl.so.3|grep -i ssl
/usr/lib/x86_64-linux-gnu/libcurl.so.3: /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0: version `OPENSSL_1.0.2' not found (required by /usr/lib/x86_64-linux-gnu/libcurl.so.3)
	libssl.so.1.0.0 => /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007fd1b8b6f000)
```
Problem is coming from libcurl3 who is using libssl.so.1.0.0. I dont understand why he is looking after OPEN_1.0.2 symbol.
 
Libssl.so.1.0.0 is missing OPENSSL_1.0.2. I tried to simlinks Libssl.so.1.1 to Libssl.so.1.0.0 but I got : 
```
/usr/lib/x86_64-linux-gnu/libssl.so.1.0.0: version `OPENSSL_1.0.1' not found (required by /usr/lib/x86_64-linux-gnu/libcurl.so.3)
/usr/lib/x86_64-linux-gnu/libssl.so.1.0.0: version `OPENSSL_1.0.2' not found (required by /usr/lib/x86_64-linux-gnu/libcurl.so.3)
/usr/lib/x86_64-linux-gnu/libssl.so.1.0.0: version `OPENSSL_1.0.0' not found (required by /usr/lib/x86_64-linux-gnu/libcurl.so.3)

``` 
```
$ dpkg -l|grep -i libssl
ii  libssl-dev:amd64                                            1.1.1b-1ubuntu2                             amd64        Secure Sockets Layer toolkit - development files
ii  libssl1.0.0:amd64                                           1.0.1t-1+deb8u11                            amd64        Secure Sockets Layer toolkit - shared libraries
ii  libssl1.1:amd64                                             1.1.1b-1ubuntu2                             amd64        Secure Sockets Layer toolkit - shared libraries
ii  libssl1.1:i386                                              1.1.1b-1ubuntu2                             i386         Secure Sockets Layer toolkit - shared libraries

$ dpkg -l|grep -i libcurl
ri  libcurl3-gnutls:amd64                                       7.64.0-2ubuntu1.1                           amd64        easy-to-use client-side URL transfer library (GnuTLS flavour)
ii  libcurl4:amd64                                              7.64.0-2ubuntu1.1                           amd64        easy-to-use client-side URL transfer library (OpenSSL flavour)
ii  libcurl4-openssl-dev:amd64                                  7.64.0-2ubuntu1.1                           amd64        development files and documentation for libcurl (OpenSSL flavour)
ii  python3-pycurl                                              7.43.0.2-0.1                                amd64        Python bindings to libcurl (Python 3)
```

I am using the last clone version of this repo. Any advices ? Should I try libssl1.0.2 ?

**Comment by brandleesee** [comment]
> I am using the last clone version of this repo.
@sam2x ...to be sure... are you using the master branch right? Version 11.
( https://github.com/brandleesee/ePSXe64Ubuntu/tree/master )
Version 12 (seperate branch) is not finished yet...

@bryceml may I call upon your expertise in this matter?
This seems right up your alley....
Thank you.

**Comment by sam2x** [comment]
Solved it. Removed the debian version of libssl1.0.0 (1.0.1t-1+deb8u11) and installed manually the one from ubuntu 16.04 (libssl1.0.0 1.0.2g) : 
https://ubuntu.pkgs.org/16.04/ubuntu-main-amd64/libssl1.0.0_1.0.2g-1ubuntu4_amd64.deb.html

It has the symbol and ePSXe launch good now :-1: 
)

**Comment by G2G2G2G** [comment]
This is still an issue on anything ubuntu 19.04 related. Out of the box this doesn't work and misses dependencies.

./ePSXe: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory

**Comment by sam2x** [comment]
> You don't have to uninstall anything, you can simply get this:
Yes, to be more clear, I removed a lib that I installed a libssl manually by myself (not the default one from ubuntu disco).

> http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.0.0_1.0.2g-1ubuntu4_amd64.deb
> and install it. This maybe should be added to the script.

Yep, this is what solved my issue. And I agree too, this would be great if this package got installed  if needed or a special notice for ubuntu >=19.04 added in the front page of this github.

**Comment by brandleesee** [comment]
@sam2x & @G2G2G2G thank you for the continuous feedback :if I may, ) do you have the necessary coding skill to pull a patch on this, please?
@bryceml you may wish to also try your hand on this one....
Thank you all!

**Comment by bryceml** [comment]
http://archive.ubuntu.com/ubuntu/pool/main/o/openssl1.0/libssl1.0.0_1.0.2n-1ubuntu5_amd64.deb looks slightly newer if that works.  It's part of the main repo for ubuntu 18.04 so it should stick around until at least 2023 in the repos.

If we're going to fetch it, since we're not doing gpg checks as part of a repo, it's best to fetch it over https, like from https://mirrors.xmission.com/ubuntu/pool/main/o/openssl1.0/libssl1.0.0_1.0.2n-1ubuntu5_amd64.deb

I haven't played with this recently so sorry I'm not of more help.

see: https://pkgs.org/download/libssl1.0.0

**Comment by brandleesee** [comment]
@bryceml no worries. thank you for the info, though. this should be helpful. meanwhile, do stick around :)
@sam2x & @G2G2G2G would you like to integrate this newer package in the script?
Thank you all.

**Comment by G2G2G2G** [comment]
Want me to test if the newer package works do you mean?

**Comment by bryceml** [comment]
https://github.com/brandleesee/ePSXe64Ubuntu/pull/12
you can try that and use it if it works.

**Comment by bryceml** [comment]
to try mine: ```wget -O ePSXe64Ubuntu.sh https://raw.githubusercontent.com/bryceml/ePSXe64Ubuntu/master/ePSXe64Ubuntu.sh && ePSXe64Ubuntu.sh```

**Comment by brandleesee** [comment]
@G2G2G2G 

> Want me to test if the newer package works do you mean?

Actually, could you test the new pull request from @bryceml and return with results?

```
wget -O ePSXe64Ubuntu.sh https://raw.githubusercontent.com/bryceml/ePSXe64Ubuntu/master/ePSXe64Ubuntu.sh && ePSXe64Ubuntu.sh
```

Thank you!

**Comment by G2G2G2G** [comment]
Yep that works fine, maybe on the front tell the people to run with 'sudo bash ePSXe64Ubuntu.sh' other than that works out of the box though, tested on an empty 19.04 install

**Comment by bryceml** [comment]
Oh yeah, I forgot to put sudo on the apt-get install and dpkg commands, I can add that tomorrow.

**Comment by bryceml** [comment]
I updated it with sudo in the correct spots if you want to test again.

**Comment by bryceml** [comment]
@G2G2G2G any update on this?

**Comment by brandleesee** [comment]
@Bryce, if you deem your updates as ready, I will simply pull up yours and update my script....
You tell me.
:)

**Comment by fcole90** [comment]
Hi, I'm testing it on Disco (19.04) too and I get the following:
```
Package ecm is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  gmp-ecm:i386 gmp-ecm
```
So I installed the package manually afterwards. Maybe it could be a good idea to add a check for that and eventually install `gmp-ecm` instead.

**Comment by fcole90** [comment]
Full output I get:
```
wget -O ePSXe64Ubuntu.sh https://raw.githubusercontent.com/brandleesee/ePSXe64Ubuntu/master/ePSXe64Ubuntu.sh && bash ePSXe64Ubuntu.sh
--2019-07-12 10:31:31--  https://raw.githubusercontent.com/brandleesee/ePSXe64Ubuntu/master/ePSXe64Ubuntu.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.240.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.240.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5429 (5.3K) [text/plain]
Saving to: ‘ePSXe64Ubuntu.sh’

ePSXe64Ubuntu.sh    100%[===================>]   5.30K  --.-KB/s    in 0.002s  

2019-07-12 10:31:31 (3.16 MB/s) - ‘ePSXe64Ubuntu.sh’ saved [5429/5429]

Welcome to ePSXe64Ubuntu.sh script, 11.4.
When ePSXe GUI appears on screen:
  Right click on icon in Dash/Dock/Panel
  Add to Favorites/Lock
  CLOSE ePSXe GUI to continue with the script.
Script started.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package ecm is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  gmp-ecm:i386 gmp-ecm

E: Package 'ecm' has no installation candidate
--2019-07-12 10:31:32--  http://archive.ubuntu.com/ubuntu/pool/main/c/curl3/libcurl3_7.58.0-2ubuntu2_amd64.deb
Resolving archive.ubuntu.com (archive.ubuntu.com)... 91.189.88.31, 91.189.88.149, 91.189.91.26, ...
Connecting to archive.ubuntu.com (archive.ubuntu.com)|91.189.88.31|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 214032 (209K) [application/x-debian-package]
Saving to: ‘/tmp/libcurl3_7.58.0-2ubuntu2_amd64.deb’

/tmp/libcurl3_7.58. 100%[===================>] 209.02K  --.-KB/s    in 0.1s    

2019-07-12 10:31:32 (1.54 MB/s) - ‘/tmp/libcurl3_7.58.0-2ubuntu2_amd64.deb’ saved [214032/214032]

/home/fabio/ePSXe: error while loading shared libraries: libSDL-1.2.so.0: cannot open shared object file: No such file or directory
sed: can't read /home/fabio/.epsxe/epsxerc: No such file or directory
sed: can't read /home/fabio/.epsxe/epsxerc: No such file or directory
cp: cannot stat '/home/fabio/ePSXe_backups/2019-07-12-10:31:31-EEST/.epsxe/docs/.': No such file or directory
Shaders Menu
1) Download
2) Restore from backup
3) Do nothing
Choose from 1 to 3 above. 1
This choice has downloaded shaders from ePSXe64Ubuntu repository.
Script finished.
```

After it finishes it doesn't work.

**Comment by fcole90** [comment]
I fixed it additionally installing the package `libsdl1.2debian`. Now it complains for:
```
/home/fabio/ePSXe: error while loading shared libraries: libSDL_ttf-2.0.so.0: cannot open shared object file: No such file or directory
```

**Comment by fcole90** [comment]
I fixed it additionally installing the package `libsdl-ttf2.0-0`. Now the program was loaded correctly.

**Comment by fcole90** [comment]
I tested it, now it works for me. I additionally installed the following packages:

- `gmp-ecm`
- `libsdl1.2debian`
- `libsdl-ttf2.0-0`

**Comment by brandleesee** [comment]
@fcole90 I noticed that you used the master branch whereas the fixes are in @bryceml's branch.
Could you test from your end using his branch and report back regarding the `ecm`, `libsdl1` and `libsdl-ttf` issues, please?
Thank you.

```wget -O ePSXe64Ubuntu.sh https://raw.githubusercontent.com/bryceml/ePSXe64Ubuntu/master/ePSXe64Ubuntu.sh && ePSXe64Ubuntu.sh```

**Comment by fcole90** [comment]
I run the script and everything seem to work, but also the previous (master) script worked, once I installed the required libraries. I checked the script, and it would require an additional check for apt failing to find `ecm`. In that case it needs to install `gmp-ecm` instead. Also, `libsdl1.2debian` is required and not installed trough the script.

**Comment by brandleesee** [comment]
@fcole90 could I ask you to paste the contents of /etc/os-release, please? 
With regards to `ecm`, it is no longer supported for arm64.
https://packages.debian.org/search?keywords=ecm
Can you confirm that the hardware you are using has arm64 architecture?
Because if not than we have to investigate further not simple add an elif....

**Comment by fcole90** [comment]
Hi, I'm definitely using a 64 bit processor, but it's amd64 not arm64.
```
$ uname -orp
5.0.0-20-generic x86_64 GNU/Linux
```

```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="19.04 (Disco Dingo)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 19.04"
VERSION_ID="19.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=disco
UBUNTU_CODENAME=disco
```

Pertaining `ecm`, I thought it had been replaced, as the `apt` output suggests:
```
Package ecm is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  gmp-ecm:i386 gmp-ecm
```
If you try to search for a package called `ecm` on dingo you don't find any [https://packages.ubuntu.com/search?mode=exactfilename&suite=disco&section=all&arch=any&keywords=ecm&searchon=names](https://packages.ubuntu.com/search?mode=exactfilename&suite=disco&section=all&arch=any&keywords=ecm&searchon=names)

Unfortunately I just noticed that the package they suggest has nothing to do with the `ecm` package that is required here. Also, in the link you sent me it seems that the latest versions were only for jessie and stretch, so it's no longer included in the latest releases like buster.. Maybe this is the reason :/

Pertaining `libsdl1.2debian` (which is an Ubuntu package despite the name), I discovered I need it by looking for the library that ePSXe was missing:
```
error while loading shared libraries: libSDL-1.2.so.0: cannot open shared object file: No such file or directory
```
So I went looking for which package provided such library (`libSDL-1.2.so.0`) in dingo and it was `libsdl1.2debian`: [https://packages.ubuntu.com/search?suite=disco&arch=any&mode=exactfilename&searchon=contents&keywords=libSDL-1.2.so.0](https://packages.ubuntu.com/search?suite=disco&arch=any&mode=exactfilename&searchon=contents&keywords=libSDL-1.2.so.0).

Pertaining `libsdl-ttf2.0-0` I suppose it was not installed because apt failed to find the `ecm` package, so it didn't install any of the mentioned packages.

**Comment by brandleesee** [comment]
@bryceml what's your take on @fcole90's report? Thanks.

**Comment by bryceml** [comment]
https://github.com/brandleesee/ePSXe64Ubuntu/pull/14

This should fix the ecm issue.

gmp-ecm looks completely unrelated to ecm

```bash
$ apt-cache show ecm
Package: ecm
Status: install ok installed
Priority: optional
Section: utils
Installed-Size: 39
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Source: cmdpack
Version: 1.03-1build1
Depends: libc6 (>= 2.14)
Description: prepares CD image files so they compress better
 The ECM format allows you to reduce the size of a typical CD image file
 (BIN, CDI, NRG, CCD, or any other format that uses raw sectors).
 It works by eliminating the Error Correction/Detection Codes (ECC/EDC) from
 each sector whenever possible. The encoder automatically adjusts to
 different sector types and automatically skips any headers it encounters.
 Since the data skipped is nearly impossible to compress with traditional
 tools, the resulting ECM file will compress far better than the raw CD image.
Description-md5: 4b08217e4d3ecc5e2b4447dc64e3fbb3
Homepage: http://www.neillcorlett.com/ecm/
Original-Maintainer: Bart Martens <bartm@debian.org>
```
```bash
$ apt-cache show gmp-ecm 
Package: gmp-ecm
Architecture: amd64
Version: 7.0.4+ds-5
Multi-Arch: foreign
Priority: optional
Section: universe/math
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian Science Maintainers <debian-science-maintainers@lists.alioth.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 311
Depends: libc6 (>= 2.7), libecm1, libgmp10 (>= 2:6.1)
Breaks: ecm (<< 1.00-2)
Replaces: ecm (<< 1.00-2)
Filename: pool/universe/g/gmp-ecm/gmp-ecm_7.0.4+ds-5_amd64.deb
Size: 108004
MD5sum: 8bd8884f8044dd1a7e20a3e4623e2f44
SHA1: b181455f3f241417255406badf2abff51d0cd848
SHA256: 8cd05639d45c315f8448d8c5789476227a4795e8df92191edfbe6db51df5c388
Homepage: https://ecm.gforge.inria.fr/
Description-en: Factor integers using the Elliptic Curve Method
 gmp-ecm is a free implementation of the Elliptic Curve Method (ECM)
 for integer factorization.
 .
 The original purpose of the ECMNET project was to make Richard Brent's
 prediction true, i.e. to find a factor of 50 digits or more by
 ECM. This goal was attained on September 14, 1998, when Conrad Curry
 found a 53-digit factor of 2^677-1 c150 using George Woltman's mprime
 program. The new goal of ECMNET is now to find other large factors by
 ecm, mainly by contributing to the Cunningham project, most likely the
 longest, ongoing computational project in history according to Bob
 Silverman. A new record was set by Nik Lygeros and Michel Mizony, who
 found in December 1999 a prime factor of 54 digits using GMP-ECM.
 .
 See http://www.loria.fr/~zimmerma/records/ecmnet.html for more
 information about ecmnet.
 .
 This package provides the command line utility.
Description-md5: aa8a1ad2382ce8ce2808bef77751b023
```

**Comment by bryceml** [comment]
The reset of the issues reported seemed to be because it couldn't find ecm and therefore failed to install a bunch of things.

**Comment by brandleesee** [comment]
@fcole90 can you test with the newly added patch?

```bash
wget -O ePSXe64Ubuntu.sh https://raw.githubusercontent.com/brandleesee/ePSXe64Ubuntu/master/ePSXe64Ubuntu.sh && bash ePSXe64Ubuntu.sh
```

If all is successful from your end will close this issue.

Thank you @bryceml as always :D

**Comment by fcole90** [comment]
@bryceml 

> gmp-ecm looks completely unrelated to ecm

Yes, it's what I discovered and wrote in the previous post :relaxed: 

> The rest of the issues reported seemed to be because it couldn't find ecm and therefore failed to install a bunch of things.

Same, I agree :blush:

**Comment by fcole90** [comment]
In the while I upgraded to eoan, but it seems to work now :blush:

**Comment by brandleesee** [comment]
Thank you @fcole90.
Am closing this issue.
If anything happens with the changes pertaining to this, I'll reopen.
