### ISSUE TITLE
Consider Flatpak / Snap package

### ISSUE THREAD

**Issue by fcole90** [brandleesee/ePSXe64Ubuntu#13]
Did you consider making a Flatpack or Snap package of ePSXe? 

I checked the licence and it says that *ePSXe is freeware and can be distributed freely as
long as it is not modified or sold and the BIOS isn't packaged with the
program*, so there is no legal concern of this.

Extract from `ePSXe205linux_x64.zip` -> `/docs/epsxe_linux_en.txt`
```
**************************************************************************
6. Legal Stuff
**************************************************************************

EPSXE Copyright 2000/2016 EPSXE team.
Sony Playstation is registered trademark of Sony.
All mentioned games are registered trademarks of their authors or marks.
You may only be in possession of the copyrighted BIOS if you're legally
entitled to do so.Neither the ePSXe Team software nor its authors are
affiliated with Sony. ePSXe is freeware and can be distributed freely as
long as it is not modified or sold and the BIOS isn't packaged with the
program. This readme must be included with the executable.

When you use this software you do that at your own risk. The authors are
not responsible for any loss or damage resulting from the use or misuse
of this software. If you do not agree with these terms delete this
software immediately !
```

**Comment by brandleesee** [comment]
I would definitely consider so. 

However, I would first need to find a developer(s) who has the necessary skills to repackage said software as Flatpak and Snap, then I would also need to escalate the plan with the original developers. Reason for the latter is that I do not want to irritate them in spite of the non-restrictive license. 

Having said so,, are you able to repackage in at least one of them, please?

I would also like the opinion of the other code contributor to this project. 
@bryceml What's your take on this? Can you repackage? Any arguments in favor or against?

**Comment by fcole90** [comment]
I packaged snaps in the past, but I would need to think how much time I can spend, I'm quite busy at the moment. I can anyway check what I can do :blush:

**Comment by brandleesee** [comment]
No rush at all!
There are, after all, no deadlines set.
This is a simple and fun project so no need for daily commitment.
Lastly, thank you for your initiative, it is appreciated.

**Comment by bryceml** [comment]
Some initial work on a snap: https://github.com/bryceml/epsxe-snap

**Comment by brandleesee** [comment]
Lovely! So can this be a collaboration between you two? (if both of you will, that is)

**Comment by bryceml** [comment]
Sure, I'll spend what spare time I have.  The place where I seem to get stuck is it can't seem to load the pulseaudio library.

**Comment by brandleesee** [comment]
Hey, am closing this.

Reason being that I like how @bryceml opened a dedicated repository for the snap.

Maybe someone knowledgeable in Flatpak can do the same.

This in no way means that I am neither interested in the Flatpak version or the Snap.

**Comment by tony** [comment]
@brandleesee I think this is still an open issue, since there isn't a release on snap store yet

**Comment by brandleesee** [comment]
This is the place for snap store's development: https://github.com/bryceml/epsxe-snap by @bryceml

**Comment by brandleesee** [comment]
Update re snap package:

https://github.com/brandleesee/ePSXe64Ubuntu/pull/23#issuecomment-729275041
