### ISSUE TITLE
Got issues with libcurl3

### ISSUE THREAD

**Issue by edwinacunav** [brandleesee/ePSXe64Ubuntu#15]
Yeah, this is just another issue with libcurl3 and epsxe...

According to Kubuntu 18.04 I've installed the following packages.
libssl1.0.0 is already the newest version (1.0.2n-1ubuntu5.3).
ecm is already the newest version (1.03-1build1).

I tried installing libcurl4-openssl-dev libssl-dev, then libcurl4-gnutls-dev libssl1.0-dev but none of them would make epsxe_x64 run...

I checked the shell script you included and noticed you would download libcurl3, extract its contents to a temporary directory so I just did it manually by looking for it on packages.ubuntu.com where it's available. Strangely its contents say it's libcurl.so.4.5.0... anyway I renamed it libcurl.so.3 but it still yells at me that it cannot open CURL_OPENSSL_3. I even dared to use okteta, KDE's hex editor, and changed it to CURL_OPENSSL_4 but ./epsxe: /usr/lib/x86_64-linux-gnu/libcurl.so.4: version `CURL_OPENSSL_4' not found (required by ./epsxe) gets printed in no time...

**Comment by brandleesee** [comment]
Thank you, @edwinacunav for the report.
@bryceml can you please look into this? Thank you.

**Comment by bryceml** [comment]
@edwinacunav if you look down more in the script, we patch epsxe to look for libcurl.so.4  you will have to also apply that patch.

**Comment by bryceml** [comment]
```bash
	  xxd /tmp/epsxe_x64 /tmp/epsxe_x64.xxd
	  patch /tmp/epsxe_x64.xxd <(echo "6434c
00019210: 2e73 6f2e 3300 6375 726c 5f65 6173 795f  .so.3.curl_easy_
.")
	  xxd -r /tmp/epsxe_x64.xxd "/home/$USER/ePSXe"
	  rm -f /tmp/epsxe_x64.xxd
```

edit the paths to work with where you have it installed.

**Comment by brandleesee** [comment]
@bryceml is this something that can be integrated into the master script, pls?

**Comment by edwinacunav** [comment]
Nah, the patch is good enough as to let me play PSX games. Curiously most of it looks exactly the same as the original code found in line 00019210. Is it magic!? O_o I know, there's no magic in programming. XD
Thanks for letting me fix it.

**Comment by brandleesee** [comment]
So this is resolved, right?
...can I/you close?

**Comment by bryceml** [comment]
@edwinacunav yeah, basically I change it to look for libcurl.so.3 instead of libcurl.so.4 .
