### ISSUE TITLE
sha256sum: WARNING: 1 computed checksum did NOT match

### ISSUE THREAD

**Issue by internet-police** [brandleesee/ePSXe64Ubuntu#18]
hi, 
it looks like the checksum for ePSXe205linux_x64.zip has changed
can you check that pls

**Comment by brandleesee** [comment]
for clarity, you are referring to this package:
http://www.epsxe.com/files/ePSXe205linux_x64.zip
if so, then I doubt I would have much control over proprietory software that is downloaded from developers' own website.

**Comment by brandleesee** [comment]
@bryceml I think I may have closed this prematurely.

Is this issue referring to this line of code?

![image](https://user-images.githubusercontent.com/12674437/84754381-995fde80-afc0-11ea-8cbb-28fccc82bace.png)

**Comment by bryceml** [comment]
probably https://github.com/brandleesee/ePSXe64Ubuntu/blob/master/ePSXe64Ubuntu.sh#L104-L10

If it doesn't patch correctly it would also complain about the hash.

**Comment by bryceml** [comment]
I just tried patching it and it had the correct hash, so either something messed up with him for the download, or the patching failed.

**Comment by brandleesee** [comment]
Ok, noted.
Maybe, @internet-police can send an error log for further investigation, please.

**Comment by internet-police** [comment]
sorry for the delay
it's been a good while since i tried this
as i remember the problem was line 104 in ePSXe64Ubuntu.sh where it would compare the checksum
for some reason that always failed for me
maybe i did something wrong

**Comment by brandleesee** [comment]
Noted, @internet-police, thank you.

@bryceml, line 104 is the same in my previous screenshot. What do you think? We keep as is and close or is there anything else that can be done? Thank you, as always.

**Comment by bryceml** [comment]
The only other thing I can think of is if something that is installed by default isn't on his system.  The complete output of `bash -x ePSXe64Ubuntu.sh` would be helpful to determine exactly what's going on.

**Comment by internet-police** [comment]
sorry for the issue
everything works fine now
dont know what caused the problem

**Comment by brandleesee** [comment]
No need to be, thanks for the interest.
