### ISSUE TITLE
Loading ISOs from CLI

### ISSUE THREAD

**Issue by mrsorensen** [brandleesee/ePSXe64Ubuntu#22]
`epsxe -loadiso PSX/Tekken\ 3/Tekken\ 3.bin `
only starts epsxe without starting the game, and 
`epsxe -loadiso PSX/Tekken\ 3/Tekken\ 3.bin -nogui`
seemingly starts the game, but with a black screen (except image of a controller in the corner) and no sound.

Is there any workaround?

**Comment by brandleesee** [comment]
Just this once you will need to access the GUI and change CPU Overclocking to 1x.
Please report back whether this was enough so I can update the README.md and close this issue.
Thank you.

**Comment by mrsorensen** [comment]
CPU Overclocking is already set to 1x. I also just noticed something in the terminal output:
```
 * Running ePSXe emulator version 2.0.5. 
 * Memory handlers init. 
 * ePSXe: PSX BIOS loaded [/home/stranger/.epsxe/bios/SCPH1001.BIN]. 
 * Loading ISO Format  * Error loading isofile: [PSX/Oddworld/Oddworld.iso]
fail
 * NTSC cdrom detected. (SLU__000.00) 
 * Init gpu core 
 * GPU supports GTE Accurate
 * Init OpenGLv2...
OpenGL Screen Resolution 1920x1200 Ratio: WidescreenVendor: Intel Open Source Technology Center
Renderer: Mesa DRI Intel(R) HD Graphics 3000 (SNB GT2)
 * Open gpu[0] 
 * Linux input init error. 
 * Init core spu ... status 0
 ok 

```
But the .iso loads just fine when loaded from GUI

**Comment by mrsorensen** [comment]
Tried running `epsxe -loadiso Oddworld.iso -nogui` which obviously has no slashes, but got the same problem. About the BIOS, it says SCPH is loaded
```
 * ePSXe: PSX BIOS loaded [/home/stranger/.epsxe/bios/SCPH1001.BIN]. 
 * Loading ISO Format  * Error loading isofile: [Oddworld.iso]
```
right before getting the error

**Comment by brandleesee** [comment]
Do you remember if you used my script to initially install ePSXe?

**Comment by brandleesee** [comment]
Was thinking that maybe you can forego the initial PS screen by using the -fastboot command.

Also please note that this script is designed to be used with the ePSXe GUI / window.

Thus, try using parts of this command which is actually for AutoHotKey on Windows:

Run C:\Users\blc\PortableApps\ePSXePortable\ePSXe.exe -fastboot -nogui -loadmemc0 "D:\ePSXe\memcards\epsxe000.mcr" -loadbin "D:\Sony - Playstation\1.cue"

Am closing this issue.
