### ISSUE TITLE
libcurl3 and libcurl4

### ISSUE THREAD

**Issue by Fallast** [brandleesee/ePSXe64Ubuntu#24]
can't have both running, so everytime i want to play open epsxe i have to uninstall libcurl4 therefore uninstalling transmission, playonlinux etc. this is annoying, is there a way to fix this? i

**Comment by brandleesee** [comment]
@bryceml Can you please look into this? Thank you.

**Comment by brandleesee** [comment]
@Fallast Can you please return with logs in way of transmission, playonlinux etc 
and also logs of epsxe when libcurl for transmission etc is installed, thank you.

**Comment by Fallast** [comment]
i don't think i'm the only one dealing with this though, it also uninstalls steam by the way haha, i will come back later with logs

**Comment by bryceml** [comment]
newer versions of the script on newer oses install the libcurl3 binary to where it goes rather that the package, so it shouldn't be necessary to uninstall anything.  What os and version of the os, and version of the script are you running?

**Comment by tobika** [comment]
Hi :)
in ubuntu 20.04 it doesn't seem possible anymore to install libcurl3

```
sudo apt install libcurl3
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package libcurl3 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libcurl4:i386 libcurl4

E: Package 'libcurl3' has no installation candidate

```

I installed `sudo apt-get install libcurl4-openssl-dev` but doesn't seem to help.

**Comment by brandleesee** [comment]
Have a look at the script at the below lines, they might be of help.

https://github.com/brandleesee/ePSXe64Ubuntu/blob/c11813057ec52f651820fa991ed048fbba58948a/ePSXe64Ubuntu.sh#L32

https://github.com/brandleesee/ePSXe64Ubuntu/blob/c11813057ec52f651820fa991ed048fbba58948a/ePSXe64Ubuntu.sh#L35-L41

https://github.com/brandleesee/ePSXe64Ubuntu/blob/c11813057ec52f651820fa991ed048fbba58948a/ePSXe64Ubuntu.sh#L52-L63

https://github.com/brandleesee/ePSXe64Ubuntu/blob/c11813057ec52f651820fa991ed048fbba58948a/ePSXe64Ubuntu.sh#L101-L105

**Comment by tobika** [comment]
thanks a lot for your fast response @brandleesee 
will try it out :)

**Comment by brandleesee** [comment]
There have been some changes in the mirror used.

You may wish to consult again the source code with the refreshed code.

We changed a particular archive.
