### ISSUE TITLE
I have a problem - the BIOS does not open 

### ISSUE THREAD

**Issue by Sidordroid** [brandleesee/ePSXe64Ubuntu#26]
Greetings. I have a problem - the BIOS does not open and does not start on this emulator. It just hangs - could you fix this error? Linux mint 20.1
![Снимок экрана от 2021-01-26 08-09-13](https://user-images.githubusercontent.com/71819151/105807585-f5570080-5fae-11eb-9d16-881744c227a1.png)

**Comment by brandleesee** [comment]
Is the memory card mounted?

**Comment by Sidordroid** [comment]
> Is the memory card mounted?

Well, of course, I mounted other memory cards to the emulator, I even slipped memory cards from the epsxe windows version in which I play

**Comment by brandleesee** [comment]
THinking about this situation, I think that if HLE is enabled then there is no active BIOS. COuld be that.
