### ISSUE TITLE
Install not working and then cannot remove.

### ISSUE THREAD

**Issue by NCJ0110** [brandleesee/ePSXe64Ubuntu#29]
I went through the install process as described in the read me and when it says :
"When ePSXe GUI appears on the screen...", it never appeared on the screen. I pressed 1 to install shaders and then I could see the Icon in the application menu, every time I clicked the icon the emulator did not open. 

Now I am stuck with the icon in my applications and it will not open, I tried to remove it based of the information in the readme but it is still there. 
Can you help me get it working or remove application please.

**Comment by rujiel** [comment]
Same for me

**Comment by jcfools** [comment]
Yep, same issue.

**Comment by Dany9966** [comment]
Hey everyone! 

To bypass this, you need to install a DEB package from here: https://packages.ubuntu.com/focal-updates/amd64/libldap-2.4-2/download

Then install it by running `sudo dpkg -i ./libldap-2.4-2_2.4.49+dfsg-2ubuntu1.9_amd64.deb`
The app's location should be at `~/.local/bin/ePSXe`, you can launch it from there.

**Comment by brandleesee** [comment]
Is this issue still relevant, please?
