### ISSUE TITLE
Can't install epsxe...

### ISSUE THREAD

**Issue by CodesoundR** [brandleesee/ePSXe64Ubuntu#30]
Hi, first of all thanks so much for this useful script!!!! 
I try to install epsxe with it, on Linux Mint 21.2 Cinnamom_x64, but unfortunately it doesn't. I don't install nothing, I only run your useful script. the output of the terminal is:

`codesound@codesound:~$ wget -O ePSXe64Ubuntu.sh https://raw.githubusercontent.com/brandleesee/ePSXe64Ubuntu/master/ePSXe64Ubuntu.sh && bash ePSXe64Ubuntu.sh
--2023-11-11 17:37:25--  https://raw.githubusercontent.com/brandleesee/ePSXe64Ubuntu/master/ePSXe64Ubuntu.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7281 (7,1K) [text/plain]
Saving to: ‘ePSXe64Ubuntu.sh’

ePSXe64Ubuntu.sh                                  100%[=============================================================================================================>]   7,11K  --.-KB/s    in 0,05s   

2023-11-11 17:37:26 (136 KB/s) - ‘ePSXe64Ubuntu.sh’ saved [7281/7281]

Welcome to ePSXe64Ubuntu.sh script, 11.6.
When ePSXe window appears on screen:
  Right click on icon in Dash/Dock/Panel
  Add to Favorites/Lock
  CLOSE ePSXe GUI to continue with the script.
Script started.
[sudo] password for codesound:           
Ign:1 http://packages.linuxmint.com victoria InRelease                                                                                                          
Hit:2 http://security.ubuntu.com/ubuntu jammy-security InRelease                                                                                                
Hit:3 https://dl.winehq.org/wine-builds/ubuntu jammy InRelease                                                                                                  
Hit:4 http://packages.linuxmint.com victoria Release                                                                                                            
Hit:5 https://ppa.launchpadcontent.net/minetestdevs/stable/ubuntu jammy InRelease               
Hit:6 http://archive.ubuntu.com/ubuntu jammy InRelease                      
Hit:8 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:9 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
sed is already the newest version (4.8-1ubuntu2).
wget is already the newest version (1.21.2-2ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
xxd is already the newest version (2:8.2.3995-1ubuntu2.13).
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libsdl-ttf2.0-0 is already the newest version (2.0.11-6).
unzip is already the newest version (6.0-26ubuntu3.1).
libncurses5 is already the newest version (6.3-2ubuntu0.1).
ecm is already the newest version (1.03-1build1).
libssl1.0.0 is already the newest version (1.0.2n-1ubuntu5).
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
--2023-11-11 17:37:33--  http://archive.ubuntu.com/ubuntu/pool/main/c/curl3/libcurl3_7.58.0-2ubuntu2_amd64.deb
Resolving archive.ubuntu.com (archive.ubuntu.com)... 185.125.190.39, 91.189.91.82, 91.189.91.83, ...
Connecting to archive.ubuntu.com (archive.ubuntu.com)|185.125.190.39|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 214032 (209K) [application/x-debian-package]
Saving to: ‘/tmp/libcurl3_7.58.0-2ubuntu2_amd64.deb’

/tmp/libcurl3_7.58.0-2ubuntu2_amd64.deb           100%[=============================================================================================================>] 209,02K   159KB/s    in 1,3s    

2023-11-11 17:37:34 (159 KB/s) - ‘/tmp/libcurl3_7.58.0-2ubuntu2_amd64.deb’ saved [214032/214032]

/tmp/libcurl3_7.58.0-2ubuntu2_amd64.deb matches provided sha256sum
/home/codesound/.local/bin/ePSXe: error while loading shared libraries: libldap_r-2.4.so.2: cannot open shared object file: No such file or directory
sed: can't read /home/codesound/.epsxe/epsxerc: No such file or directory
sed: can't read /home/codesound/.epsxe/epsxerc: No such file or directory
cp: cannot stat '/home/codesound/ePSXe_backups/2023-11-11-17:37:26-CET/.epsxe/bios/.': No such file or directory
cp: cannot stat '/home/codesound/ePSXe_backups/2023-11-11-17:37:26-CET/.epsxe/cheats/.': No such file or directory
cp: cannot stat '/home/codesound/ePSXe_backups/2023-11-11-17:37:26-CET/.epsxe/config/.': No such file or directory
cp: cannot stat '/home/codesound/ePSXe_backups/2023-11-11-17:37:26-CET/.epsxe/configs/.': No such file or directory
cp: cannot stat '/home/codesound/ePSXe_backups/2023-11-11-17:37:26-CET/.epsxe/covers/.': No such file or directory
cp: cannot stat '/home/codesound/ePSXe_backups/2023-11-11-17:37:26-CET/.epsxe/idx/.': No such file or directory
cp: cannot stat '/home/codesound/ePSXe_backups/2023-11-11-17:37:26-CET/.epsxe/info/.': No such file or directory
cp: cannot stat '/home/codesound/ePSXe_backups/2023-11-11-17:37:26-CET/.epsxe/memcards/.': No such file or directory
cp: cannot stat '/home/codesound/ePSXe_backups/2023-11-11-17:37:26-CET/.epsxe/patches/.': No such file or directory
cp: cannot stat '/home/codesound/ePSXe_backups/2023-11-11-17:37:26-CET/.epsxe/plugins/.': No such file or directory
cp: cannot stat '/home/codesound/ePSXe_backups/2023-11-11-17:37:26-CET/.epsxe/sstates/.': No such file or directory
Shaders Menu
1) Download
2) Restore from backup
3) Do nothing
Choose from 1 to 3 above. 1
This choice has downloaded shaders from ePSXe64Ubuntu repository.
Script finished.
`
Can you please help me to understand how to fix it?
Thanks

**Comment by brandleesee** [comment]
Hi, thank you for the compliment, I am grateful.

The script is obsolete since ePSXe for Linux is no longer maintained by the original developers.

So, may I suggest Duckstation?
It is a very modern alternative to ePSXe.

Otherwise, please return with screenshots of the trouble you are experiencing. I'll try to help as best I can.

**Comment by CodesoundR** [comment]
Hi, thanks! Duckstation is very Beautiful! Thanks for the suggestion! Bye

Il giorno dom 12 nov 2023 alle ore 14:20 Brandon Lee Camilleri <
***@***.***> ha scritto:
